import vehiclesData from './vehicles.json';

export type FuelType = 'gasoline' | 'diesel';

export interface VehicleSpec {
  year: number;
  make: string;
  model: string;
  combinedMpg: number;
  tankCapacityGal: number;
  fuelType: FuelType;
}

export interface VehicleLookups {
  years(): number[];
  makesFor(year: number): string[];
  modelsFor(year: number, make: string): string[];
  findVehicle(year: number, make: string, model: string): VehicleSpec | undefined;
}

/** Build the cascading year → make → model lookups over a vehicle list. */
export function makeVehicleLookups(specs: VehicleSpec[]): VehicleLookups {
  return {
    years: () => [...new Set(specs.map((v) => v.year))].sort((a, b) => b - a),
    makesFor: (year) =>
      [...new Set(specs.filter((v) => v.year === year).map((v) => v.make))].sort(),
    modelsFor: (year, make) =>
      specs
        .filter((v) => v.year === year && v.make === make)
        .map((v) => v.model)
        .sort(),
    findVehicle: (year, make, model) =>
      specs.find((v) => v.year === year && v.make === make && v.model === model),
  };
}

/**
 * The bundled dataset: EPA combined MPG merged with curated tank capacities,
 * generated by scripts/build-vehicles.mjs. Regenerate with `npm run build:data`.
 */
export const vehicleLookups = makeVehicleLookups(vehiclesData as VehicleSpec[]);
